import 'dart:async';
import 'dart:io' show Platform;

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// The ringback tone the CALLER hears while the other phone rings.
///
/// # Why this exists
///
/// Founder report, 25 Aug 2026: "when u call someone ur phone dosent
/// [ring] like what whatsapp does". They are right, and it is not a
/// cosmetic gap. On a real phone network the ringback is generated by
/// the network, not by either handset — so a VoIP call that renders only
/// a status label gives the caller *silence* while they wait. Silence
/// during a wait is indistinguishable from a broken call, and the
/// documented reaction is to hang up and try again, which costs a call
/// setup, a push, and the callee's second interruption.
///
/// The tone is 440 Hz + 480 Hz, two seconds on and four off — the
/// standard call-progress cadence, synthesised into
/// `assets/sounds/call/ringback.wav` rather than licensed. That exact
/// rhythm is what makes it read as "their phone is ringing" rather than
/// as a notification chime; people have been trained on it for decades.
///
/// # What it deliberately does NOT do
///
///  * **It does not touch the audio session.** [CallAudio] owns that —
///    the mode, the focus and the route. This player just plays into
///    whatever route is already selected, so the tone comes out of the
///    earpiece if that is where the call is, and follows the member to
///    Bluetooth when they switch.
///  * **It does not handle the INCOMING ringtone.** That is the OS's
///    job through CallKit / the Android telecom stack, which rings
///    correctly even when the app is dead. Playing our own on top would
///    double it.
///
/// # Fail-soft, like every other sound in this app
///
/// Every call is guarded. A handset that refuses to play this must
/// still complete the call — losing the tone is a worse call, losing
/// the call is a bug.
class CallTones {
  CallTones._();

  static const String _ringbackAsset = 'sounds/call/ringback.wav';

  static AudioPlayer? _player;
  static bool _wantRingback = false;

  /// Start the ringback, if it is not already going.
  ///
  /// Idempotent: the call state machine can pass through `initiating`
  /// and `ringing` in quick succession and both want the tone, so
  /// calling this twice must not restart it from the top or layer a
  /// second copy over the first.
  static Future<void> startRingback() async {
    if (_wantRingback) return;
    _wantRingback = true;
    try {
      final player = _player ??= AudioPlayer();
      // Loop the 6-second cadence for as long as it rings. The asset is
      // enveloped at both ends of the burst so the seam is silent —
      // without that the loop point clicks on every repeat.
      await player.setReleaseMode(ReleaseMode.loop);
      await player.setVolume(0.55);
      await _configureForCall(player);
      // Re-check: `await` gaps above mean the call could have been
      // answered or cancelled while we were setting up, and starting the
      // tone after that would play it over live audio.
      if (!_wantRingback) return;
      await player.play(AssetSource(_ringbackAsset));
    } catch (e) {
      debugPrint('CallTones.startRingback failed (call continues): $e');
    }
  }

  /// Stop it. Safe to call when nothing is playing, which is most of the
  /// times it gets called — every terminal phase routes through here.
  static Future<void> stopRingback() async {
    _wantRingback = false;
    final player = _player;
    if (player == null) return;
    try {
      await player.stop();
    } catch (e) {
      debugPrint('CallTones.stopRingback failed: $e');
    }
  }

  /// Release the player. Called when the call screen is done with.
  static Future<void> dispose() async {
    _wantRingback = false;
    final player = _player;
    _player = null;
    if (player == null) return;
    try {
      await player.dispose();
    } catch (e) {
      debugPrint('CallTones.dispose failed: $e');
    }
  }

  /// Tell the platform this is call audio, not media.
  ///
  /// It matters for two reasons the member would notice: the volume keys
  /// have to adjust the CALL stream (so turning the ringback down turns
  /// the call down, which is what they expect), and the tone has to come
  /// out of the earpiece when the call is on the earpiece rather than
  /// blaring from the loudspeaker with the phone against their head.
  ///
  /// Focus is deliberately left alone — [CallAudio] has already taken
  /// it for the call, and asking again here would duck the call's own
  /// audio the moment it connects.
  static Future<void> _configureForCall(AudioPlayer player) async {
    if (kIsWeb) return;
    try {
      await player.setAudioContext(
        AudioContext(
          android: const AudioContextAndroid(
            isSpeakerphoneOn: false,
            stayAwake: true,
            contentType: AndroidContentType.speech,
            usageType: AndroidUsageType.voiceCommunication,
            audioFocus: AndroidAudioFocus.none,
          ),
          iOS: AudioContextIOS(
            category: AVAudioSessionCategory.playAndRecord,
            options: const {
              AVAudioSessionOptions.allowBluetooth,
              AVAudioSessionOptions.allowBluetoothA2DP,
            },
          ),
        ),
      );
    } catch (e) {
      // A platform that refuses the context still plays the tone, just
      // possibly on the media stream. Better than no tone.
      debugPrint('CallTones could not set the call audio context: $e');
      if (!Platform.isAndroid && !Platform.isIOS) return;
    }
  }
}
