import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/hymn_model.dart';
import 'cache_service.dart';

/// Reads the Hymnal.
///
/// ## 100% offline by design
///
/// The hymns are BUNDLED at `assets/hymns/hymns.json` (generated by
/// `dart run scripts/export_hymns.dart`). The read path — [cached], [all],
/// [search] — never touches the network and can never fail, so the Hymnal
/// opens instantly on a fresh install in airplane mode. This replaces the old
/// behaviour where every open hit Supabase and showed a spinner or an error
/// when the connection was flaky.
///
/// A network refresh still exists, but it is strictly opt-in ([refresh], wired
/// to pull-to-refresh only) and purely additive: it merges hymns the admin
/// added since the last app release into a Hive overlay. If it fails, nothing
/// is surfaced to the user — the bundled hymns are already on screen.
class HymnService {
  HymnService._();

  static const _assetPath = 'assets/hymns/hymns.json';

  /// Hive key holding hymns added in Supabase AFTER this build's asset was
  /// generated. Merged over the bundled list by id.
  static const _overlayKey = 'hymns_overlay_v2';

  static List<Hymn>? _mem;
  static bool _assetLoaded = false;

  /// Drop the in-memory list so the next read re-merges. Called after an admin
  /// adds/edits/removes a hymn.
  static void invalidate() => _mem = null;

  /// The hymns, read synchronously. Returns whatever is already in memory;
  /// empty only before [warmUp] / [all] has run once in this process.
  ///
  /// Lets the Hymnal tab paint its first frame with real content instead of a
  /// spinner.
  static List<Hymn> cached() => _mem ?? const [];

  /// True once the bundled asset has been parsed, so the UI can tell
  /// "still loading" from "genuinely empty".
  static bool get isReady => _assetLoaded;

  /// Parses the bundled asset (once) and merges any Hive overlay.
  /// Safe to call repeatedly — subsequent calls are a memory read.
  static Future<List<Hymn>> all() async {
    final mem = _mem;
    if (mem != null) return mem;

    final bundled = await _loadAsset();
    final merged = _mergeOverlay(bundled);
    _assetLoaded = true;
    return _mem = merged;
  }

  /// Kick off asset parsing early (e.g. when the Library screen mounts) so the
  /// Hymnal tab is instant when the user swipes to it.
  static Future<void> warmUp() => all();

  static Future<List<Hymn>> _loadAsset() async {
    try {
      final raw = await rootBundle.loadString(_assetPath);
      // Tolerate a BOM the same way BibleService does.
      final clean = raw.startsWith('﻿') ? raw.substring(1) : raw;
      return (jsonDecode(clean) as List)
          .map((r) => Hymn.fromJson(r as Map<String, dynamic>))
          .toList();
    } catch (e) {
      // A missing/corrupt asset is a build error, not a user-facing one. Fall
      // back to the overlay alone so the app still shows whatever it has.
      debugPrint('HymnService: bundled asset unreadable ($e)');
      return const [];
    }
  }

  /// Merges the Hive overlay over [bundled], keyed by id. Overlay entries win
  /// (they're newer), and ids absent from the bundle are appended.
  static List<Hymn> _mergeOverlay(List<Hymn> bundled) {
    final overlay = _readOverlay();
    if (overlay.isEmpty) return _sorted(bundled);
    final byId = {for (final h in bundled) h.id: h};
    for (final h in overlay) {
      byId[h.id] = h;
    }
    return _sorted(byId.values.toList());
  }

  static List<Hymn> _sorted(List<Hymn> list) {
    final out = list.toList()
      ..sort((a, b) {
        final c = a.collection.compareTo(b.collection);
        if (c != 0) return c;
        final an = a.number ?? 1 << 30;
        final bn = b.number ?? 1 << 30;
        if (an != bn) return an.compareTo(bn);
        return a.title.compareTo(b.title);
      });
    return out;
  }

  static List<Hymn> _readOverlay() {
    try {
      final raw = CacheService.readStringStale(_overlayKey);
      if (raw == null) return const [];
      return (jsonDecode(raw) as List)
          .map((r) => Hymn.fromJson(r as Map<String, dynamic>))
          .toList();
    } catch (_) {
      return const [];
    }
  }

  /// OPT-IN network refresh, wired to pull-to-refresh only.
  ///
  /// Pulls the full published list and stores anything that differs from the
  /// bundled asset as an overlay. Returns true when something changed.
  /// Never throws and never surfaces an error — the bundled hymns are already
  /// on screen, so a failed refresh is a non-event.
  static Future<bool> refresh() async {
    try {
      final rows = await Supabase.instance.client
          .from('hymns')
          .select('id,number,title,lyrics,language,category,collection')
          .eq('is_published', true)
          .order('number', ascending: true)
          .timeout(const Duration(seconds: 12));

      final remote = (rows as List)
          .map((r) => Hymn.fromJson(r as Map<String, dynamic>))
          .toList();
      if (remote.isEmpty) return false;

      final bundled = await _loadAsset();
      final bundledIds = {for (final h in bundled) h.id: h};

      // Only persist genuine deltas so the overlay stays small instead of
      // duplicating the whole bundled hymnal into Hive.
      final delta = <Hymn>[];
      for (final h in remote) {
        final existing = bundledIds[h.id];
        if (existing == null ||
            existing.title != h.title ||
            existing.lyrics != h.lyrics ||
            existing.number != h.number ||
            existing.collection != h.collection) {
          delta.add(h);
        }
      }

      final before = _readOverlay().length;
      await CacheService.writeString(
        _overlayKey,
        jsonEncode([
          for (final h in delta)
            {
              'id': h.id,
              'number': h.number,
              'title': h.title,
              'lyrics': h.lyrics,
              'language': h.language,
              'category': h.category,
              'collection': h.collection,
            },
        ]),
      );
      invalidate();
      await all();
      return delta.length != before;
    } catch (e) {
      debugPrint('HymnService.refresh skipped: $e');
      return false;
    }
  }

  /// Local search across number, title and lyrics. A bare number matches the
  /// hymn number exactly first (so "23" jumps to hymn 23), then falls back to
  /// substring matches on title/lyrics. All words must appear.
  static Future<List<Hymn>> search(String query) async {
    final hymns = await all();
    return searchIn(hymns, query);
  }

  /// Synchronous variant over an already-loaded list — lets the tab filter on
  /// every keystroke with no await, so the field never lags the finger.
  static List<Hymn> searchIn(List<Hymn> hymns, String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return hymns;

    final asNumber = int.tryParse(q);
    final terms = q.split(RegExp(r'\s+')).where((t) => t.isNotEmpty).toList();

    final scored = <(int, Hymn)>[];
    for (final h in hymns) {
      final titleLower = h.title.toLowerCase();
      final hay = '${h.number ?? ''} $titleLower ${h.lyrics.toLowerCase()}';
      if (!terms.every(hay.contains)) continue;
      var score = 0;
      if (asNumber != null && h.number == asNumber) score += 1000;
      if (titleLower == q) score += 400;
      if (titleLower.startsWith(q)) score += 150;
      if (titleLower.contains(q)) score += 100;
      scored.add((score, h));
    }
    scored.sort((a, b) {
      if (a.$1 != b.$1) return b.$1.compareTo(a.$1);
      final an = a.$2.number ?? 1 << 30;
      final bn = b.$2.number ?? 1 << 30;
      return an.compareTo(bn);
    });
    return scored.map((e) => e.$2).toList();
  }

  /// Distinct categories present in [hymns], for the browse-by-theme chips.
  static List<String> categoriesIn(List<Hymn> hymns) {
    final set = <String>{};
    for (final h in hymns) {
      final c = h.category;
      if (c != null && c.trim().isNotEmpty) set.add(c.trim());
    }
    final list = set.toList()..sort();
    return list;
  }
}
