-- =====================================================================
--  PATCH 242 — Advent AI: Bible book aliases
--
--  Resolves what people and models actually write ("Ps", "1 Cor",
--  "Revelations", "Song of Songs") to a canonical book number, so the
--  edge function does not need a regex thicket to find a passage.
--
--  Aliases are normalised: lowercase, punctuation and spaces stripped.
--  bible_book_number() applies the same normalisation to its input, so
--  "1 Cor.", "1cor" and "I Corinthians" all land on the same row.
--
--  Requires patch 241 (schema). IDEMPOTENT: yes.
-- =====================================================================

INSERT INTO public.bible_book_aliases (alias, book_number, book_name) VALUES
  ('ge', 1, 'Genesis'),
  ('gen', 1, 'Genesis'),
  ('genesis', 1, 'Genesis'),
  ('gn', 1, 'Genesis'),
  ('ex', 2, 'Exodus'),
  ('exo', 2, 'Exodus'),
  ('exod', 2, 'Exodus'),
  ('exodus', 2, 'Exodus'),
  ('lev', 3, 'Leviticus'),
  ('leviticus', 3, 'Leviticus'),
  ('lv', 3, 'Leviticus'),
  ('nm', 4, 'Numbers'),
  ('nu', 4, 'Numbers'),
  ('num', 4, 'Numbers'),
  ('numbers', 4, 'Numbers'),
  ('deu', 5, 'Deuteronomy'),
  ('deut', 5, 'Deuteronomy'),
  ('deuteronomy', 5, 'Deuteronomy'),
  ('dt', 5, 'Deuteronomy'),
  ('jos', 6, 'Joshua'),
  ('josh', 6, 'Joshua'),
  ('joshua', 6, 'Joshua'),
  ('jdg', 7, 'Judges'),
  ('judg', 7, 'Judges'),
  ('judges', 7, 'Judges'),
  ('rth', 8, 'Ruth'),
  ('ru', 8, 'Ruth'),
  ('ruth', 8, 'Ruth'),
  ('1sa', 9, '1 Samuel'),
  ('1sam', 9, '1 Samuel'),
  ('1samuel', 9, '1 Samuel'),
  ('firstsamuel', 9, '1 Samuel'),
  ('isam', 9, '1 Samuel'),
  ('2sa', 10, '2 Samuel'),
  ('2sam', 10, '2 Samuel'),
  ('2samuel', 10, '2 Samuel'),
  ('iisam', 10, '2 Samuel'),
  ('secondsamuel', 10, '2 Samuel'),
  ('1kgs', 11, '1 Kings'),
  ('1ki', 11, '1 Kings'),
  ('1kings', 11, '1 Kings'),
  ('ikings', 11, '1 Kings'),
  ('2kgs', 12, '2 Kings'),
  ('2ki', 12, '2 Kings'),
  ('2kings', 12, '2 Kings'),
  ('iikings', 12, '2 Kings'),
  ('1ch', 13, '1 Chronicles'),
  ('1chr', 13, '1 Chronicles'),
  ('1chronicles', 13, '1 Chronicles'),
  ('ichronicles', 13, '1 Chronicles'),
  ('2ch', 14, '2 Chronicles'),
  ('2chr', 14, '2 Chronicles'),
  ('2chronicles', 14, '2 Chronicles'),
  ('iichronicles', 14, '2 Chronicles'),
  ('ezr', 15, 'Ezra'),
  ('ezra', 15, 'Ezra'),
  ('ne', 16, 'Nehemiah'),
  ('neh', 16, 'Nehemiah'),
  ('nehemiah', 16, 'Nehemiah'),
  ('est', 17, 'Esther'),
  ('esth', 17, 'Esther'),
  ('esther', 17, 'Esther'),
  ('jb', 18, 'Job'),
  ('job', 18, 'Job'),
  ('ps', 19, 'Psalms'),
  ('psa', 19, 'Psalms'),
  ('psalm', 19, 'Psalms'),
  ('psalms', 19, 'Psalms'),
  ('pss', 19, 'Psalms'),
  ('pr', 20, 'Proverbs'),
  ('prov', 20, 'Proverbs'),
  ('proverbs', 20, 'Proverbs'),
  ('prv', 20, 'Proverbs'),
  ('ecc', 21, 'Ecclesiastes'),
  ('eccl', 21, 'Ecclesiastes'),
  ('ecclesiastes', 21, 'Ecclesiastes'),
  ('qoheleth', 21, 'Ecclesiastes'),
  ('canticles', 22, 'Song of Solomon'),
  ('song', 22, 'Song of Solomon'),
  ('songofsolomon', 22, 'Song of Solomon'),
  ('songofsongs', 22, 'Song of Solomon'),
  ('sos', 22, 'Song of Solomon'),
  ('is', 23, 'Isaiah'),
  ('isa', 23, 'Isaiah'),
  ('isaiah', 23, 'Isaiah'),
  ('je', 24, 'Jeremiah'),
  ('jer', 24, 'Jeremiah'),
  ('jeremiah', 24, 'Jeremiah'),
  ('la', 25, 'Lamentations'),
  ('lam', 25, 'Lamentations'),
  ('lamentations', 25, 'Lamentations'),
  ('eze', 26, 'Ezekiel'),
  ('ezek', 26, 'Ezekiel'),
  ('ezekiel', 26, 'Ezekiel'),
  ('ezk', 26, 'Ezekiel'),
  ('dan', 27, 'Daniel'),
  ('daniel', 27, 'Daniel'),
  ('dn', 27, 'Daniel'),
  ('ho', 28, 'Hosea'),
  ('hos', 28, 'Hosea'),
  ('hosea', 28, 'Hosea'),
  ('jl', 29, 'Joel'),
  ('joe', 29, 'Joel'),
  ('joel', 29, 'Joel'),
  ('am', 30, 'Amos'),
  ('amos', 30, 'Amos'),
  ('ob', 31, 'Obadiah'),
  ('obad', 31, 'Obadiah'),
  ('obadiah', 31, 'Obadiah'),
  ('jnh', 32, 'Jonah'),
  ('jon', 32, 'Jonah'),
  ('jonah', 32, 'Jonah'),
  ('mi', 33, 'Micah'),
  ('mic', 33, 'Micah'),
  ('micah', 33, 'Micah'),
  ('na', 34, 'Nahum'),
  ('nah', 34, 'Nahum'),
  ('nahum', 34, 'Nahum'),
  ('hab', 35, 'Habakkuk'),
  ('habakkuk', 35, 'Habakkuk'),
  ('hb', 35, 'Habakkuk'),
  ('zep', 36, 'Zephaniah'),
  ('zeph', 36, 'Zephaniah'),
  ('zephaniah', 36, 'Zephaniah'),
  ('hag', 37, 'Haggai'),
  ('haggai', 37, 'Haggai'),
  ('hg', 37, 'Haggai'),
  ('zec', 38, 'Zechariah'),
  ('zech', 38, 'Zechariah'),
  ('zechariah', 38, 'Zechariah'),
  ('mal', 39, 'Malachi'),
  ('malachi', 39, 'Malachi'),
  ('ml', 39, 'Malachi'),
  ('mat', 40, 'Matthew'),
  ('matt', 40, 'Matthew'),
  ('matthew', 40, 'Matthew'),
  ('mt', 40, 'Matthew'),
  ('mark', 41, 'Mark'),
  ('mk', 41, 'Mark'),
  ('mrk', 41, 'Mark'),
  ('lk', 42, 'Luke'),
  ('luk', 42, 'Luke'),
  ('luke', 42, 'Luke'),
  ('jn', 43, 'John'),
  ('joh', 43, 'John'),
  ('john', 43, 'John'),
  ('act', 44, 'Acts'),
  ('acts', 44, 'Acts'),
  ('actsoftheapostles', 44, 'Acts'),
  ('rm', 45, 'Romans'),
  ('ro', 45, 'Romans'),
  ('rom', 45, 'Romans'),
  ('romans', 45, 'Romans'),
  ('1co', 46, '1 Corinthians'),
  ('1cor', 46, '1 Corinthians'),
  ('1corinthians', 46, '1 Corinthians'),
  ('icorinthians', 46, '1 Corinthians'),
  ('2co', 47, '2 Corinthians'),
  ('2cor', 47, '2 Corinthians'),
  ('2corinthians', 47, '2 Corinthians'),
  ('iicorinthians', 47, '2 Corinthians'),
  ('ga', 48, 'Galatians'),
  ('gal', 48, 'Galatians'),
  ('galatians', 48, 'Galatians'),
  ('ep', 49, 'Ephesians'),
  ('eph', 49, 'Ephesians'),
  ('ephesians', 49, 'Ephesians'),
  ('phil', 50, 'Philippians'),
  ('philippians', 50, 'Philippians'),
  ('php', 50, 'Philippians'),
  ('col', 51, 'Colossians'),
  ('colossians', 51, 'Colossians'),
  ('1th', 52, '1 Thessalonians'),
  ('1thess', 52, '1 Thessalonians'),
  ('1thessalonians', 52, '1 Thessalonians'),
  ('ithessalonians', 52, '1 Thessalonians'),
  ('2th', 53, '2 Thessalonians'),
  ('2thess', 53, '2 Thessalonians'),
  ('2thessalonians', 53, '2 Thessalonians'),
  ('iithessalonians', 53, '2 Thessalonians'),
  ('1ti', 54, '1 Timothy'),
  ('1tim', 54, '1 Timothy'),
  ('1timothy', 54, '1 Timothy'),
  ('itimothy', 54, '1 Timothy'),
  ('2ti', 55, '2 Timothy'),
  ('2tim', 55, '2 Timothy'),
  ('2timothy', 55, '2 Timothy'),
  ('iitimothy', 55, '2 Timothy'),
  ('ti', 56, 'Titus'),
  ('tit', 56, 'Titus'),
  ('titus', 56, 'Titus'),
  ('philemon', 57, 'Philemon'),
  ('phlm', 57, 'Philemon'),
  ('phm', 57, 'Philemon'),
  ('hbr', 58, 'Hebrews'),
  ('heb', 58, 'Hebrews'),
  ('hebrews', 58, 'Hebrews'),
  ('james', 59, 'James'),
  ('jas', 59, 'James'),
  ('jm', 59, 'James'),
  ('1pe', 60, '1 Peter'),
  ('1pet', 60, '1 Peter'),
  ('1peter', 60, '1 Peter'),
  ('ipeter', 60, '1 Peter'),
  ('2pe', 61, '2 Peter'),
  ('2pet', 61, '2 Peter'),
  ('2peter', 61, '2 Peter'),
  ('iipeter', 61, '2 Peter'),
  ('1jn', 62, '1 John'),
  ('1jo', 62, '1 John'),
  ('1john', 62, '1 John'),
  ('ijohn', 62, '1 John'),
  ('2jn', 63, '2 John'),
  ('2jo', 63, '2 John'),
  ('2john', 63, '2 John'),
  ('iijohn', 63, '2 John'),
  ('3jn', 64, '3 John'),
  ('3jo', 64, '3 John'),
  ('3john', 64, '3 John'),
  ('iiijohn', 64, '3 John'),
  ('jd', 65, 'Jude'),
  ('jud', 65, 'Jude'),
  ('jude', 65, 'Jude'),
  ('apocalypse', 66, 'Revelation'),
  ('re', 66, 'Revelation'),
  ('rev', 66, 'Revelation'),
  ('revelation', 66, 'Revelation'),
  ('revelations', 66, 'Revelation')
ON CONFLICT (alias) DO UPDATE
  SET book_number = EXCLUDED.book_number,
      book_name   = EXCLUDED.book_name;

DO $$
DECLARE v_books INT;
BEGIN
  SELECT COUNT(DISTINCT book_number) INTO v_books
    FROM public.bible_book_aliases;
  IF v_books <> 66 THEN
    RAISE EXCEPTION 'patch 242: expected 66 books, found %', v_books;
  END IF;
  RAISE NOTICE 'patch 242 OK — % aliases across 66 books',
    (SELECT COUNT(*) FROM public.bible_book_aliases);
END $$;
