-- patch_162: Bible Quiz content batch 5 — Sabbath, Law, Salvation, Doctrine,
-- Prophecy, Adventist History, Spirit of Prophecy, Health, Christian Living,
-- Stewardship, and a new Church & Mission category (with Solusi, so the
-- history isn't only North American).

insert into public.quiz_questions (question, options, correct_index, explanation, reference, category, difficulty) values

-- ---- Sabbath --------------------------------------------------------------
('For whom did Jesus say the Sabbath was made?', '["For the Jews only", "For man", "For the priests", "For the angels"]'::jsonb, 1, '"The sabbath was made for man, and not man for the sabbath."', 'Mark 2:27', 'Sabbath', 'easy'),
('What was Jesus'' custom on the Sabbath day?', '["To rest at home", "To go into the synagogue", "To travel", "To fast"]'::jsonb, 1, '"And, as his custom was, he went into the synagogue on the sabbath day."', 'Luke 4:16', 'Sabbath', 'medium'),
('What did the women do on the Sabbath after Jesus was crucified?', '["They anointed the body", "They rested according to the commandment", "They returned to Galilee", "They met with the disciples"]'::jsonb, 1, 'Even at the cross, the commandment was honoured.', 'Luke 23:56', 'Sabbath', 'medium'),
('In the new earth, how often will all flesh come to worship?', '["Once a year", "From one sabbath to another", "Every morning only", "It does not say"]'::jsonb, 1, '"From one new moon to another, and from one sabbath to another."', 'Isaiah 66:23', 'Sabbath', 'medium'),
('What did God say the Sabbath is a sign of?', '["A covenant of land", "That the LORD sanctifies His people", "The priesthood", "The seasons"]'::jsonb, 1, '"That they might know that I am the LORD that sanctify them."', 'Ezekiel 20:12', 'Sabbath', 'hard'),
('Which commandment begins with the word "Remember"?', '["The first", "The third", "The fourth", "The tenth"]'::jsonb, 2, '"Remember the sabbath day, to keep it holy."', 'Exodus 20:8', 'Sabbath', 'easy'),
('How many days are we given to labour, according to the fourth commandment?', '["Five", "Six", "Seven", "As many as needed"]'::jsonb, 1, '"Six days shalt thou labour, and do all thy work."', 'Exodus 20:9', 'Sabbath', 'easy'),
('In Isaiah 58:13, what are we to call the Sabbath?', '["A burden", "A delight", "A fast", "A tradition"]'::jsonb, 1, '"Call the sabbath a delight, the holy of the LORD, honourable."', 'Isaiah 58:13', 'Sabbath', 'medium'),
('Whose Sabbath-keeping custom is recorded in Acts 17:2?', '["Peter''s", "Paul''s", "Barnabas''", "Timothy''s"]'::jsonb, 1, '"And Paul, as his manner was... three sabbath days reasoned with them out of the scriptures."', 'Acts 17:2', 'Sabbath', 'hard'),
('Who blessed and sanctified the seventh day?', '["Moses", "God", "Israel", "The prophets"]'::jsonb, 1, 'God rested, blessed and sanctified it at creation — before any nation existed.', 'Genesis 2:2-3', 'Sabbath', 'easy'),
('Who else is included in the Sabbath rest by the fourth commandment?', '["Only the head of the house", "Sons, daughters, servants, cattle and the stranger", "Only Israelites", "Only priests"]'::jsonb, 1, 'The rest extends to the whole household, and even to the animals.', 'Exodus 20:10', 'Sabbath', 'medium'),
('Which day did God bless as the memorial of creation?', '["The first day", "The seventh day", "The eighth day", "Every day equally"]'::jsonb, 1, 'The Sabbath is the sign that God is Creator.', 'Exodus 20:11', 'Sabbath', 'easy'),

-- ---- Law ------------------------------------------------------------------
('Which is the first commandment with promise?', '["Thou shalt not kill", "Honour thy father and thy mother", "Remember the sabbath day", "Thou shalt not steal"]'::jsonb, 1, '"That it may be well with thee, and thou mayest live long on the earth."', 'Ephesians 6:2-3', 'Law', 'medium'),
('What is the fifth commandment?', '["Thou shalt not steal", "Honour thy father and thy mother", "Thou shalt not covet", "Remember the sabbath day"]'::jsonb, 1, 'The first commandment of the second table, concerning our duty to others.', 'Exodus 20:12', 'Law', 'easy'),
('Which commandment forbids coveting?', '["The eighth", "The ninth", "The tenth", "The seventh"]'::jsonb, 2, '"Thou shalt not covet thy neighbour''s house..."', 'Exodus 20:17', 'Law', 'medium'),
('Where were the tables of stone kept?', '["In the Holy Place", "In the ark of the covenant", "In Moses'' tent", "In the courtyard"]'::jsonb, 1, '"And I put the tables in the ark which I had made."', 'Deuteronomy 10:5', 'Law', 'medium'),
('According to Romans 7:12, the law is holy, just and what?', '["Heavy", "Good", "Temporary", "Hidden"]'::jsonb, 1, '"Wherefore the law is holy, and the commandment holy, and just, and good."', 'Romans 7:12', 'Law', 'medium'),
('By the law is the knowledge of what?', '["Salvation", "Sin", "Wisdom", "Prophecy"]'::jsonb, 1, 'The law is the mirror that shows us our need of a Saviour.', 'Romans 3:20', 'Law', 'medium'),
('Complete: "If ye love me, keep my ___."', '["traditions", "commandments", "feasts", "counsel"]'::jsonb, 1, 'Obedience is the fruit of love, never the price of it.', 'John 14:15', 'Law', 'easy'),
('What is love, according to Romans 13:10?', '["A feeling", "The fulfilling of the law", "A gift only", "The end of the law"]'::jsonb, 1, '"Love worketh no ill to his neighbour: therefore love is the fulfilling of the law."', 'Romans 13:10', 'Law', 'medium'),
('Where did Moses place the book of the law?', '["Inside the ark", "In the side of the ark", "On the altar", "In the tabernacle door"]'::jsonb, 1, 'The ceremonial law was placed beside the ark; the Ten Commandments were inside it.', 'Deuteronomy 31:24-26', 'Law', 'hard'),
('Complete: "Whosoever shall keep the whole law, and yet offend in one point, he is ___."', '["forgiven", "guilty of all", "counted righteous", "under grace"]'::jsonb, 1, 'The law is one whole — which is why we need a Saviour, not a scorecard.', 'James 2:10', 'Law', 'medium'),
('What did Jesus say about the law and the prophets?', '["He came to destroy them", "He came not to destroy, but to fulfil", "They ended at John", "They applied only to Israel"]'::jsonb, 1, '"Till heaven and earth pass, one jot or one tittle shall in no wise pass from the law."', 'Matthew 5:17-18', 'Law', 'medium'),
('According to 1 John 3:4, what is sin?', '["A mistake", "The transgression of the law", "A weakness", "An illness"]'::jsonb, 1, '"Whosoever committeth sin transgresseth also the law."', '1 John 3:4', 'Law', 'easy'),

-- ---- Salvation ------------------------------------------------------------
('What must a man be to see the kingdom of God?', '["Circumcised", "Born again", "Wealthy", "A Levite"]'::jsonb, 1, 'Jesus told Nicodemus, "Except a man be born again, he cannot see the kingdom of God."', 'John 3:3', 'Salvation', 'easy'),
('Complete: "If we confess our sins, he is faithful and just to ___ us our sins."', '["remind", "forgive", "judge", "test"]'::jsonb, 1, '"...and to cleanse us from all unrighteousness."', '1 John 1:9', 'Salvation', 'easy'),
('Who did Jesus say is the only way to the Father?', '["Moses", "The law", "Himself", "The church"]'::jsonb, 2, '"I am the way, the truth, and the life: no man cometh unto the Father, but by me."', 'John 14:6', 'Salvation', 'easy'),
('Complete: "All have sinned, and come short of the ___ of God."', '["law", "glory", "mercy", "kingdom"]'::jsonb, 1, 'Every person stands in the same need of grace.', 'Romans 3:23', 'Salvation', 'easy'),
('Why is salvation not of works?', '["Because works are evil", "Lest any man should boast", "Because the law is abolished", "Because God does not see them"]'::jsonb, 1, 'Grace leaves no room for pride.', 'Ephesians 2:8-9', 'Salvation', 'medium'),
('Who stands at the door and knocks?', '["The Holy Spirit", "Jesus", "An angel", "The watchman"]'::jsonb, 1, '"If any man hear my voice, and open the door, I will come in to him."', 'Revelation 3:20', 'Salvation', 'easy'),
('What did Jesus promise the thief on the cross?', '["Nothing", "That he would be with Him in paradise", "A resurrection that day", "Healing"]'::jsonb, 1, 'A dying man was saved by faith alone, with no time for works.', 'Luke 23:43', 'Salvation', 'medium'),
('Being justified by faith, what do we have with God?', '["Wealth", "Peace", "Authority", "Immunity"]'::jsonb, 1, '"Therefore being justified by faith, we have peace with God through our Lord Jesus Christ."', 'Romans 5:1', 'Salvation', 'medium'),
('Complete: "Come unto me, all ye that labour and are heavy laden, and I will give you ___."', '["work", "rest", "riches", "wisdom"]'::jsonb, 1, 'The invitation is to everyone who is weary.', 'Matthew 11:28', 'Salvation', 'easy'),
('There is none other name under heaven whereby we must be what?', '["Judged", "Saved", "Numbered", "Blessed"]'::jsonb, 1, 'Peter preached that salvation is in Christ alone.', 'Acts 4:12', 'Salvation', 'medium'),
('Whom does the Lord chasten?', '["His enemies", "Whom he loveth", "The careless only", "No one"]'::jsonb, 1, '"For whom the Lord loveth he chasteneth."', 'Hebrews 12:6', 'Salvation', 'medium'),
('What is the gift of God, in contrast to the wages of sin?', '["Long life on earth", "Eternal life through Jesus Christ", "Prosperity", "Wisdom"]'::jsonb, 1, '"For the wages of sin is death; but the gift of God is eternal life."', 'Romans 6:23', 'Salvation', 'easy'),

-- ---- Doctrine -------------------------------------------------------------
('Whom did Jesus name in the baptismal formula?', '["The Father, the Son and the Holy Ghost", "Abraham, Isaac and Jacob", "Moses and Elijah", "The apostles"]'::jsonb, 0, 'The three Persons of the Godhead are named together.', 'Matthew 28:19', 'Doctrine', 'easy'),
('What name did Jesus give the Holy Spirit?', '["The Judge", "The Comforter", "The Messenger", "The Witness only"]'::jsonb, 1, '"But the Comforter, which is the Holy Ghost, whom the Father will send in my name."', 'John 14:26', 'Doctrine', 'medium'),
('What is the church called in 1 Corinthians 12:27?', '["The temple of stone", "The body of Christ", "The vineyard", "The flock of Israel"]'::jsonb, 1, 'Every member has a place and a gift.', '1 Corinthians 12:27', 'Doctrine', 'medium'),
('Where was marriage instituted?', '["At Sinai", "In Eden, at creation", "In Canaan", "In the temple"]'::jsonb, 1, '"Therefore shall a man leave his father and his mother, and shall cleave unto his wife."', 'Genesis 2:24', 'Doctrine', 'medium'),
('Who is the head of the church?', '["Peter", "Christ", "The apostles", "The elders"]'::jsonb, 1, '"For the husband is the head of the wife, even as Christ is the head of the church."', 'Ephesians 5:23', 'Doctrine', 'easy'),
('In the Lord''s Supper, what does the bread represent?', '["The law", "Christ''s body", "The church", "The harvest"]'::jsonb, 1, '"Take, eat; this is my body."', 'Matthew 26:26', 'Doctrine', 'easy'),
('Which ordinance did Jesus institute by washing the disciples'' feet?', '["Baptism", "The ordinance of humility", "Anointing", "Ordination"]'::jsonb, 1, '"Ye also ought to wash one another''s feet."', 'John 13:14-15', 'Doctrine', 'medium'),
('What is the greatest commandment, according to Jesus?', '["Keep the sabbath", "Love the Lord thy God with all thy heart", "Honour thy parents", "Do not steal"]'::jsonb, 1, 'And the second is like unto it — love thy neighbour as thyself.', 'Matthew 22:37-39', 'Doctrine', 'easy'),
('Whom has God appointed to judge the world?', '["Moses", "The apostles", "Jesus Christ", "The angels"]'::jsonb, 2, '"He hath appointed a day, in the which he will judge the world in righteousness by that man whom he hath ordained."', 'Acts 17:31', 'Doctrine', 'medium'),
('What does it mean to be born of water and of the Spirit?', '["To be baptized and made new by the Spirit", "To be born in Israel", "To be anointed king", "To keep the feasts"]'::jsonb, 0, 'Jesus explained the new birth to Nicodemus.', 'John 3:5', 'Doctrine', 'medium'),
('According to Hebrews, how many times did Christ offer Himself?', '["Yearly", "Once for all", "Daily", "Twice"]'::jsonb, 1, '"Christ was once offered to bear the sins of many."', 'Hebrews 9:28', 'Doctrine', 'medium'),
('What is the whole duty of man, according to Ecclesiastes?', '["To gain wisdom", "Fear God, and keep his commandments", "To build", "To rest"]'::jsonb, 1, '"Let us hear the conclusion of the whole matter."', 'Ecclesiastes 12:13', 'Doctrine', 'medium'),

-- ---- Prophecy -------------------------------------------------------------
('In Daniel 2, what kingdom did the breast and arms of silver represent?', '["Babylon", "Medo-Persia", "Greece", "Rome"]'::jsonb, 1, 'A kingdom inferior to Babylon would arise after it — Medo-Persia.', 'Daniel 2:32, 39', 'Prophecy', 'medium'),
('In Daniel 2, what did the belly and thighs of brass represent?', '["Medo-Persia", "Greece", "Rome", "Egypt"]'::jsonb, 1, 'The third kingdom of brass was Greece under Alexander.', 'Daniel 2:32, 39', 'Prophecy', 'medium'),
('In Daniel 2, what did the legs of iron represent?', '["Greece", "Rome", "Babylon", "Assyria"]'::jsonb, 1, 'Iron — strong as iron, breaking all before it — was Rome.', 'Daniel 2:33, 40', 'Prophecy', 'medium'),
('What do the feet of iron mixed with clay represent?', '["A united empire", "The divided kingdoms that followed Rome", "The church", "Israel restored"]'::jsonb, 1, 'Partly strong, partly broken — they shall not cleave one to another.', 'Daniel 2:41-43', 'Prophecy', 'medium'),
('What is the stone cut out without hands?', '["Israel", "The kingdom God shall set up, which shall stand for ever", "The church of Rome", "The temple"]'::jsonb, 1, 'It smote the image and became a great mountain filling the whole earth.', 'Daniel 2:44-45', 'Prophecy', 'medium'),
('In Daniel 7, which beast represented Babylon?', '["The lion", "The bear", "The leopard", "The dreadful beast"]'::jsonb, 0, 'The lion with eagle''s wings — Babylon.', 'Daniel 7:4', 'Prophecy', 'medium'),
('In Daniel 7, what did the bear represent?', '["Babylon", "Medo-Persia", "Greece", "Rome"]'::jsonb, 1, 'Raised up on one side, with three ribs in its mouth.', 'Daniel 7:5', 'Prophecy', 'medium'),
('In Daniel 7, what did the leopard with four heads represent?', '["Babylon", "Medo-Persia", "Greece", "Rome"]'::jsonb, 2, 'Four heads — Alexander''s empire divided among four generals.', 'Daniel 7:6', 'Prophecy', 'hard'),
('How many horns were plucked up before the little horn?', '["One", "Two", "Three", "Seven"]'::jsonb, 2, '"Before whom there were three of the first horns plucked up by the roots."', 'Daniel 7:8', 'Prophecy', 'hard'),
('In Daniel 8, what did the ram with two horns represent?', '["Greece", "The kings of Media and Persia", "Rome", "Egypt"]'::jsonb, 1, 'The angel Gabriel named it plainly.', 'Daniel 8:20', 'Prophecy', 'medium'),
('In Daniel 8, what did the rough goat represent?', '["Babylon", "Persia", "Greece", "Rome"]'::jsonb, 2, '"And the rough goat is the king of Grecia."', 'Daniel 8:21', 'Prophecy', 'medium'),
('What does the first angel''s message call people to give to God?', '["Tithe", "Glory", "Sacrifice", "Silence"]'::jsonb, 1, '"Fear God, and give glory to him; for the hour of his judgment is come."', 'Revelation 14:7', 'Prophecy', 'medium'),
('What does the second angel announce?', '["The judgment is come", "Babylon is fallen", "The mark of the beast", "The gospel to every nation"]'::jsonb, 1, '"Babylon is fallen, is fallen, that great city."', 'Revelation 14:8', 'Prophecy', 'medium'),
('What does the third angel warn against receiving?', '["The seal of God", "The mark of the beast", "False riches", "A false prophet"]'::jsonb, 1, 'The third angel gives the most solemn warning in Scripture.', 'Revelation 14:9-11', 'Prophecy', 'medium'),
('What is the number of the beast in Revelation 13?', '["616", "666", "777", "144"]'::jsonb, 1, '"It is the number of a man; and his number is Six hundred threescore and six."', 'Revelation 13:18', 'Prophecy', 'easy'),
('How many churches are addressed in Revelation 2 and 3?', '["Three", "Five", "Seven", "Twelve"]'::jsonb, 2, 'Ephesus, Smyrna, Pergamos, Thyatira, Sardis, Philadelphia and Laodicea.', 'Revelation 2-3', 'Prophecy', 'easy'),
('Who is the great dragon of Revelation 12?', '["Rome", "That old serpent, called the Devil, and Satan", "Babylon", "The false prophet"]'::jsonb, 1, 'He was cast out into the earth, and his angels with him.', 'Revelation 12:9', 'Prophecy', 'medium'),
('The 70 weeks of Daniel 9 point to the coming of whom?', '["Cyrus", "The Messiah", "Nehemiah", "Antiochus"]'::jsonb, 1, '"Unto the Messiah the Prince shall be seven weeks, and threescore and two weeks."', 'Daniel 9:25', 'Prophecy', 'hard'),

-- ---- Adventist History ----------------------------------------------------
('Which Baptist preacher led the Advent awakening of the 1840s?', '["Joseph Bates", "William Miller", "James White", "Hiram Edson"]'::jsonb, 1, 'William Miller preached that Christ would return about 1843-1844.', '-', 'Adventist History', 'medium'),
('What date is known as the Great Disappointment?', '["22 October 1844", "1 January 1844", "22 October 1843", "14 March 1845"]'::jsonb, 0, 'When Jesus did not return as expected, the believers were bitterly disappointed.', '-', 'Adventist History', 'medium'),
('Who first brought the seventh-day Sabbath to the Advent believers?', '["Ellen White", "Rachel Oakes Preston", "Joseph Bates", "John Byington"]'::jsonb, 1, 'A Seventh Day Baptist, she shared the Sabbath truth in Washington, New Hampshire.', '-', 'Adventist History', 'hard'),
('Which former sea captain became a leading advocate of the Sabbath?', '["James White", "Joseph Bates", "J.N. Andrews", "Uriah Smith"]'::jsonb, 1, 'Joseph Bates wrote an influential tract on the seventh-day Sabbath.', '-', 'Adventist History', 'medium'),
('In what year was the Seventh-day Adventist Church formally organized?', '["1844", "1860", "1863", "1874"]'::jsonb, 2, 'The General Conference was organized in 1863.', '-', 'Adventist History', 'medium'),
('In what year was the name "Seventh-day Adventist" chosen?', '["1844", "1860", "1863", "1888"]'::jsonb, 1, 'The name was adopted in 1860, expressing both the Sabbath and the advent hope.', '-', 'Adventist History', 'hard'),
('Who was the first president of the General Conference?', '["James White", "John Byington", "Joseph Bates", "George Butler"]'::jsonb, 1, 'John Byington served as the first General Conference president in 1863.', '-', 'Adventist History', 'hard'),
('Who was the first official Seventh-day Adventist missionary sent overseas?', '["J.N. Andrews", "Joseph Bates", "Uriah Smith", "Stephen Haskell"]'::jsonb, 0, 'J.N. Andrews was sent to Switzerland in 1874.', '-', 'Adventist History', 'hard'),
('Which mission station, founded in 1894, was the first Adventist mission to Africans in what is now Zimbabwe?', '["Solusi", "Malamulo", "Helderberg", "Bethel"]'::jsonb, 0, 'Solusi Mission in Matabeleland became the church''s first mission to indigenous Africans, and later Solusi University.', '-', 'Adventist History', 'medium'),
('Which health institution opened in Battle Creek in 1866?', '["The Western Health Reform Institute", "Loma Linda Sanitarium", "The Review and Herald", "Andrews University"]'::jsonb, 0, 'It later became the famous Battle Creek Sanitarium.', '-', 'Adventist History', 'hard'),
('Which doctor led the Battle Creek Sanitarium?', '["John Harvey Kellogg", "J.N. Loughborough", "Uriah Smith", "Merritt Kellogg"]'::jsonb, 0, 'Dr John Harvey Kellogg directed the sanitarium for many years.', '-', 'Adventist History', 'medium'),
('Where is the world headquarters of the Seventh-day Adventist Church today?', '["Battle Creek, Michigan", "Silver Spring, Maryland", "Loma Linda, California", "Washington DC"]'::jsonb, 1, 'The General Conference has been in Silver Spring, Maryland since 1989.', '-', 'Adventist History', 'medium'),
('Whom did Ellen Harmon marry in 1846?', '["Joseph Bates", "James White", "John Byington", "Hiram Edson"]'::jsonb, 1, 'James and Ellen White laboured together for the rest of his life.', '-', 'Adventist History', 'medium'),
('What was the first Adventist periodical, published in 1849?', '["The Review and Herald", "The Present Truth", "Signs of the Times", "The Youth''s Instructor"]'::jsonb, 1, 'James White began publishing The Present Truth in 1849.', '-', 'Adventist History', 'hard'),

-- ---- Spirit of Prophecy ---------------------------------------------------
('What was Ellen White''s maiden name?', '["Harmon", "Edson", "Bates", "Andrews"]'::jsonb, 0, 'She was born Ellen Gould Harmon in Gorham, Maine, in 1827.', '-', 'Spirit of Prophecy', 'medium'),
('In what year did Ellen Harmon receive her first vision?', '["1840", "1844", "1850", "1863"]'::jsonb, 1, 'Her first vision came in December 1844, shortly after the Great Disappointment.', '-', 'Spirit of Prophecy', 'medium'),
('Which Ellen White book presents the life of Christ?', '["The Great Controversy", "The Desire of Ages", "Education", "Steps to Christ"]'::jsonb, 1, 'The Desire of Ages was published in 1898.', '-', 'Spirit of Prophecy', 'easy'),
('Which book traces the conflict from Jerusalem''s destruction to the new earth?', '["Patriarchs and Prophets", "The Great Controversy", "Prophets and Kings", "The Acts of the Apostles"]'::jsonb, 1, 'The Great Controversy closes the Conflict of the Ages series.', '-', 'Spirit of Prophecy', 'medium'),
('Which Ellen White book explains the parables of Jesus?', '["Christ''s Object Lessons", "Thoughts from the Mount of Blessing", "Steps to Christ", "Education"]'::jsonb, 0, 'Christ''s Object Lessons was published in 1900.', '-', 'Spirit of Prophecy', 'medium'),
('Which book expounds the Sermon on the Mount?', '["Education", "Thoughts from the Mount of Blessing", "The Ministry of Healing", "Early Writings"]'::jsonb, 1, 'Published in 1896.', '-', 'Spirit of Prophecy', 'hard'),
('Which Ellen White book deals with health and healing ministry?', '["The Ministry of Healing", "Counsels on Diet", "Education", "Steps to Christ"]'::jsonb, 0, 'The Ministry of Healing was published in 1905.', '-', 'Spirit of Prophecy', 'medium'),
('What is the subject of "Steps to Christ"?', '["Church organization", "Coming to Christ and the Christian life", "Prophecy", "Health reform"]'::jsonb, 1, 'It is her most widely translated book.', '-', 'Spirit of Prophecy', 'easy'),
('By what test are all prophetic claims to be measured?', '["Popularity", "To the law and to the testimony", "Miracles alone", "Church councils"]'::jsonb, 1, '"If they speak not according to this word, it is because there is no light in them."', 'Isaiah 8:20', 'Spirit of Prophecy', 'medium'),
('Jesus said false prophets are known by what?', '["Their words", "Their fruits", "Their dress", "Their following"]'::jsonb, 1, '"Ye shall know them by their fruits."', 'Matthew 7:16', 'Spirit of Prophecy', 'easy'),
('The testimony of Jesus is the spirit of what?', '["Truth", "Prophecy", "Wisdom", "Grace"]'::jsonb, 1, '"For the testimony of Jesus is the spirit of prophecy."', 'Revelation 19:10', 'Spirit of Prophecy', 'medium'),
('In what year did Ellen White die?', '["1901", "1915", "1888", "1920"]'::jsonb, 1, 'She died on 16 July 1915 at Elmshaven, California.', '-', 'Spirit of Prophecy', 'hard'),
('Which book covers the Old Testament from creation to David?', '["Prophets and Kings", "Patriarchs and Prophets", "The Great Controversy", "Early Writings"]'::jsonb, 1, 'Patriarchs and Prophets opens the Conflict of the Ages series.', '-', 'Spirit of Prophecy', 'hard'),

-- ---- Health ---------------------------------------------------------------
('What diet did Daniel and his friends request in Babylon?', '["The king''s meat", "Pulse to eat and water to drink", "Bread and wine", "Fish only"]'::jsonb, 1, 'They asked to be proved for ten days on simple food.', 'Daniel 1:12', 'Health', 'easy'),
('How did Daniel and his friends look after the ten days?', '["Weaker", "Fairer and fatter in flesh than all the others", "The same", "Sickly"]'::jsonb, 1, 'God honoured their faithfulness in a small thing.', 'Daniel 1:15', 'Health', 'easy'),
('Complete: "Whether therefore ye eat, or drink... do all to the ___ of God."', '["glory", "praise", "service", "law"]'::jsonb, 0, 'Even eating and drinking are acts of worship.', '1 Corinthians 10:31', 'Health', 'easy'),
('Which land animals did Leviticus 11 identify as clean?', '["Those that chew the cud and part the hoof", "Those that fly", "Those that live in herds", "All of them"]'::jsonb, 0, 'Both marks had to be present.', 'Leviticus 11:3', 'Health', 'medium'),
('Which water creatures were identified as clean?', '["Those with fins and scales", "All fish", "Shellfish", "Those in rivers only"]'::jsonb, 0, '"Whatsoever hath fins and scales in the waters... those shall ye eat."', 'Leviticus 11:9', 'Health', 'medium'),
('Complete: "Wine is a ___, strong drink is raging."', '["comfort", "mocker", "medicine", "blessing"]'::jsonb, 1, '"...and whosoever is deceived thereby is not wise."', 'Proverbs 20:1', 'Health', 'medium'),
('Complete: "A merry heart doeth good like a ___."', '["medicine", "fountain", "fire", "song"]'::jsonb, 0, '"But a broken spirit drieth the bones."', 'Proverbs 17:22', 'Health', 'medium'),
('What did John wish for Gaius in 3 John 2?', '["Riches", "That he would prosper and be in health", "Long travels", "Many friends"]'::jsonb, 1, '"...even as thy soul prospereth."', '3 John 2', 'Health', 'medium'),
('Whose mother was told to drink no wine or strong drink before his birth?', '["Samuel''s", "Samson''s", "David''s", "Isaac''s"]'::jsonb, 1, 'Samson was to be a Nazarite unto God from the womb.', 'Judges 13:4-5', 'Health', 'hard'),
('Complete: "Look not thou upon the wine when it is ___."', '["poured", "red", "sweet", "old"]'::jsonb, 1, '"At the last it biteth like a serpent, and stingeth like an adder."', 'Proverbs 23:31-32', 'Health', 'medium'),
('What does Paul call the body in 1 Corinthians 6:19?', '["A vessel of clay", "The temple of the Holy Ghost", "A tent", "A garment"]'::jsonb, 1, '"...ye are not your own... therefore glorify God in your body."', '1 Corinthians 6:19-20', 'Health', 'easy'),
('What was John the Baptist told he should not drink?', '["Water", "Wine nor strong drink", "Milk", "Vinegar"]'::jsonb, 1, 'He was filled with the Holy Ghost from his mother''s womb.', 'Luke 1:15', 'Health', 'medium'),

-- ---- Christian Living -----------------------------------------------------
('What is the first fruit of the Spirit listed in Galatians 5:22?', '["Joy", "Love", "Peace", "Faith"]'::jsonb, 1, 'Love heads the list, and the rest flow from it.', 'Galatians 5:22', 'Christian Living', 'easy'),
('In the armour of God, what is the shield?', '["Truth", "Faith", "Righteousness", "Salvation"]'::jsonb, 1, '"Above all, taking the shield of faith."', 'Ephesians 6:16', 'Christian Living', 'medium'),
('What is the sword of the Spirit?', '["Prayer", "The word of God", "Faith", "The gospel"]'::jsonb, 1, 'The only offensive weapon in the armour.', 'Ephesians 6:17', 'Christian Living', 'medium'),
('Complete: "A soft answer turneth away ___."', '["wrath", "shame", "envy", "sorrow"]'::jsonb, 0, '"But grievous words stir up anger."', 'Proverbs 15:1', 'Christian Living', 'easy'),
('What is the Golden Rule?', '["Do unto others as ye would that men should do to you", "An eye for an eye", "Love only your neighbour", "Judge righteously"]'::jsonb, 0, '"For this is the law and the prophets."', 'Matthew 7:12', 'Christian Living', 'easy'),
('How often did Jesus say we should forgive?', '["Seven times", "Until seventy times seven", "Three times", "Once"]'::jsonb, 1, 'Peter thought seven was generous; Jesus removed the limit.', 'Matthew 18:21-22', 'Christian Living', 'easy'),
('Complete: "Pray without ___."', '["fear", "ceasing", "doubting", "boasting"]'::jsonb, 1, '"In every thing give thanks: for this is the will of God."', '1 Thessalonians 5:17-18', 'Christian Living', 'easy'),
('How are we told to overcome evil?', '["With strength", "With good", "With silence", "With the law"]'::jsonb, 1, '"Be not overcome of evil, but overcome evil with good."', 'Romans 12:21', 'Christian Living', 'medium'),
('What did Jesus say to do to your enemies?', '["Avoid them", "Love them, and pray for them", "Report them", "Rebuke them"]'::jsonb, 1, '"Love your enemies, bless them that curse you."', 'Matthew 5:44', 'Christian Living', 'easy'),
('Complete: "Trust in the LORD with all thine heart; and lean not unto thine own ___."', '["strength", "understanding", "riches", "counsel"]'::jsonb, 1, '"In all thy ways acknowledge him, and he shall direct thy paths."', 'Proverbs 3:5-6', 'Christian Living', 'easy'),
('Complete: "Be ye kind one to another, tenderhearted, ___ one another."', '["teaching", "forgiving", "warning", "judging"]'::jsonb, 1, '"...even as God for Christ''s sake hath forgiven you."', 'Ephesians 4:32', 'Christian Living', 'easy'),
('Philippians 4:8 tells us to think on things that are true, honest, just, pure, lovely and what else?', '["Profitable", "Of good report", "Popular", "Ancient"]'::jsonb, 1, '"If there be any virtue, and if there be any praise, think on these things."', 'Philippians 4:8', 'Christian Living', 'medium'),

-- ---- Stewardship ----------------------------------------------------------
('Complete: "Bring ye all the tithes into the ___."', '["temple", "storehouse", "city", "altar"]'::jsonb, 1, '"...and prove me now herewith, saith the LORD of hosts."', 'Malachi 3:10', 'Stewardship', 'easy'),
('What does God promise those who bring their tithe?', '["Fame", "To open the windows of heaven and pour out a blessing", "Political power", "Longer life only"]'::jsonb, 1, '"...that there shall not be room enough to receive it."', 'Malachi 3:10', 'Stewardship', 'easy'),
('According to Malachi 3:8, how had the people robbed God?', '["In sacrifices", "In tithes and offerings", "In vows", "In the temple treasury"]'::jsonb, 1, '"Will a man rob God? Yet ye have robbed me."', 'Malachi 3:8', 'Stewardship', 'medium'),
('Who received tithe from Abraham?', '["Melchizedek", "Aaron", "Pharaoh", "Lot"]'::jsonb, 0, 'Melchizedek, king of Salem and priest of the most high God.', 'Genesis 14:20; Hebrews 7:2', 'Stewardship', 'medium'),
('What portion did Jacob vow to give God at Bethel?', '["A fifth", "A tenth", "A half", "All"]'::jsonb, 1, '"Of all that thou shalt give me I will surely give the tenth unto thee."', 'Genesis 28:22', 'Stewardship', 'medium'),
('Complete: "The earth is the LORD''s, and the ___ thereof."', '["glory", "fulness", "peoples", "harvest"]'::jsonb, 1, 'Everything we hold is on loan from God.', 'Psalm 24:1', 'Stewardship', 'medium'),
('What kind of giver does God love?', '["A generous one", "A cheerful giver", "A quiet one", "A wealthy one"]'::jsonb, 1, '"Not grudgingly, or of necessity: for God loveth a cheerful giver."', '2 Corinthians 9:7', 'Stewardship', 'easy'),
('What did Jesus say about the widow''s two mites?', '["It was too little", "She cast in more than they all", "She should have kept them", "It was a private matter"]'::jsonb, 1, 'She gave of her want, all that she had.', 'Mark 12:43-44', 'Stewardship', 'easy'),
('Where did Jesus say to lay up treasure?', '["In barns", "In heaven", "In the temple", "With the poor only"]'::jsonb, 1, '"For where your treasure is, there will your heart be also."', 'Matthew 6:20-21', 'Stewardship', 'easy'),
('Complete: "It is more blessed to give than to ___."', '["keep", "receive", "lend", "spend"]'::jsonb, 1, 'Paul quoted these words of the Lord Jesus.', 'Acts 20:35', 'Stewardship', 'easy'),
('Whose are the silver and the gold, according to Haggai?', '["The king''s", "God''s", "The priests''", "The people''s"]'::jsonb, 1, '"The silver is mine, and the gold is mine, saith the LORD of hosts."', 'Haggai 2:8', 'Stewardship', 'medium'),
('In the parable of the talents, what did the unfaithful servant do with his one talent?', '["Spent it", "Hid it in the earth", "Gave it away", "Doubled it"]'::jsonb, 1, 'He was condemned not for losing it, but for doing nothing with it.', 'Matthew 25:18', 'Stewardship', 'medium'),

-- ---- Church & Mission (new category) --------------------------------------
('Where is the Great Commission found?', '["Matthew 28:19-20", "John 3:16", "Acts 2:38", "Romans 10:9"]'::jsonb, 0, '"Go ye therefore, and teach all nations."', 'Matthew 28:19-20', 'Church & Mission', 'easy'),
('Where were the disciples first called Christians?', '["Jerusalem", "Antioch", "Rome", "Corinth"]'::jsonb, 1, '"And the disciples were called Christians first in Antioch."', 'Acts 11:26', 'Church & Mission', 'medium'),
('Who preached the sermon on the day of Pentecost?', '["Paul", "Peter", "Stephen", "James"]'::jsonb, 1, 'Peter stood up with the eleven and lifted up his voice.', 'Acts 2:14', 'Church & Mission', 'medium'),
('About how many were added to the church at Pentecost?', '["Three hundred", "One thousand", "Three thousand", "Five thousand"]'::jsonb, 2, '"And the same day there were added unto them about three thousand souls."', 'Acts 2:41', 'Church & Mission', 'medium'),
('Who was the first Christian martyr?', '["James", "Stephen", "Peter", "Paul"]'::jsonb, 1, 'Stephen was stoned while Saul consented to his death.', 'Acts 7:59-60', 'Church & Mission', 'medium'),
('On the road to which city was Saul converted?', '["Jerusalem", "Damascus", "Antioch", "Joppa"]'::jsonb, 1, 'A light from heaven shone round about him near Damascus.', 'Acts 9:3', 'Church & Mission', 'easy'),
('Which gifts did Christ give to the church in Ephesians 4:11?', '["Apostles, prophets, evangelists, pastors and teachers", "Kings and priests", "Judges and elders", "Deacons only"]'::jsonb, 0, 'Given for the perfecting of the saints and the work of the ministry.', 'Ephesians 4:11-12', 'Church & Mission', 'medium'),
('Who was the seller of purple who opened her home to Paul in Philippi?', '["Priscilla", "Lydia", "Dorcas", "Phebe"]'::jsonb, 1, '"Whose heart the Lord opened, that she attended unto the things which were spoken of Paul."', 'Acts 16:14-15', 'Church & Mission', 'hard'),
('On what foundation is the church built?', '["Peter alone", "The apostles and prophets, Jesus Christ being the chief corner stone", "The law", "Tradition"]'::jsonb, 1, 'The whole building fitly framed together groweth unto an holy temple.', 'Ephesians 2:20-21', 'Church & Mission', 'medium'),
('Which disciple was known for making garments for the poor and was raised by Peter?', '["Lydia", "Dorcas (Tabitha)", "Mary", "Martha"]'::jsonb, 1, '"This woman was full of good works and almsdeeds."', 'Acts 9:36-40', 'Church & Mission', 'hard');

-- Safety net: these batches were written against a bank that already held
-- 158 questions, and seven of them collided with existing rows. Re-running
-- any of these files is now harmless.
delete from public.quiz_questions q
 where q.id > (select min(q2.id) from public.quiz_questions q2
                where q2.question = q.question);
