-- patch_161: Bible Quiz content batch 4 — the doctrinal categories.
-- Sanctuary, Baptism, State of the Dead and Creation were the thinnest in
-- the bank (Sanctuary and Baptism had one question each); this brings them
-- all well above the lobby's 5-question floor.

insert into public.quiz_questions (question, options, correct_index, explanation, reference, category, difficulty) values

-- ---- Sanctuary ------------------------------------------------------------
('What stood in the Most Holy Place of the earthly sanctuary?', '["The altar of incense", "The ark of the covenant", "The table of shewbread", "The laver"]'::jsonb, 1, 'Behind the second veil stood the ark of the covenant.', 'Hebrews 9:3-4', 'Sanctuary', 'medium'),
('What was placed inside the ark of the covenant?', '["The tables of the covenant", "The book of the law", "The priestly garments", "The incense"]'::jsonb, 0, 'God''s law, written on stone, was placed in the ark beneath the mercy seat.', 'Deuteronomy 10:4-5; Hebrews 9:4', 'Sanctuary', 'medium'),
('What separated the Holy Place from the Most Holy Place?', '["A stone wall", "The second veil", "A curtain of gold", "The mercy seat"]'::jsonb, 1, '"And after the second veil, the tabernacle which is called the Holiest of all."', 'Hebrews 9:3', 'Sanctuary', 'medium'),
('On the Day of Atonement, where did the high priest go?', '["The courtyard", "The Holy Place", "The Most Holy Place", "The city gate"]'::jsonb, 2, 'Once a year the high priest entered the Most Holy Place with blood.', 'Leviticus 16; Hebrews 9:7', 'Sanctuary', 'medium'),
('What happened to the scapegoat on the Day of Atonement?', '["It was sacrificed", "It was sent away into the wilderness", "It was given to the priests", "It was burned outside the camp"]'::jsonb, 1, 'The sins of the people were confessed over it and it was led away.', 'Leviticus 16:21-22', 'Sanctuary', 'hard'),
('Who is our High Priest in the heavenly sanctuary?', '["Aaron", "Melchizedek", "Jesus", "Michael"]'::jsonb, 2, '"We have such an high priest, who is set on the right hand of the throne of the Majesty in the heavens."', 'Hebrews 8:1-2', 'Sanctuary', 'easy'),
('The earthly sanctuary was a pattern of what?', '["Solomon''s temple", "The sanctuary in heaven", "The synagogue", "The Garden of Eden"]'::jsonb, 1, 'Moses was told to make all things according to the pattern shown him in the mount.', 'Hebrews 8:5; Exodus 25:40', 'Sanctuary', 'medium'),
('What did the lamb slain in the sanctuary service point forward to?', '["The Passover meal", "Jesus, the Lamb of God", "The priesthood", "The covenant with Abraham"]'::jsonb, 1, '"Behold the Lamb of God, which taketh away the sin of the world."', 'John 1:29', 'Sanctuary', 'easy'),
('Where did God say He would meet with His people?', '["At the altar", "Above the mercy seat, between the cherubims", "At the door of the tent", "On Mount Sinai only"]'::jsonb, 1, '"There I will meet with thee, and I will commune with thee from above the mercy seat."', 'Exodus 25:22', 'Sanctuary', 'hard'),
('What happened to the temple veil when Jesus died?', '["It caught fire", "It was rent in twain from the top to the bottom", "It was taken down by the priests", "Nothing"]'::jsonb, 1, 'Torn from top to bottom — the way into God''s presence was opened by heaven.', 'Matthew 27:51', 'Sanctuary', 'medium'),
('According to Daniel 8:14, what would happen after the 2300 days?', '["The temple would be rebuilt", "The sanctuary would be cleansed", "The Messiah would be born", "Israel would return"]'::jsonb, 1, 'Adventists understand this as the beginning of the judgment in 1844.', 'Daniel 8:14', 'Sanctuary', 'medium'),
('Who was Israel''s first high priest?', '["Moses", "Aaron", "Eleazar", "Melchizedek"]'::jsonb, 1, 'Aaron and his sons were set apart to minister in the priest''s office.', 'Exodus 28:1', 'Sanctuary', 'easy'),
('What two items stood in the courtyard of the sanctuary?', '["The altar of burnt offering and the laver", "The ark and the mercy seat", "The candlestick and the table", "The altar of incense and the veil"]'::jsonb, 0, 'The sacrifice was offered, then the priest washed at the laver.', 'Exodus 40:29-30', 'Sanctuary', 'hard'),
('Which three articles of furniture stood in the Holy Place?', '["Ark, mercy seat and cherubims", "Table of shewbread, candlestick and altar of incense", "Laver, altar and ark", "Candlestick, laver and veil"]'::jsonb, 1, 'Bread, light and intercession — a picture of Christ''s ministry for us.', 'Exodus 25-30; Hebrews 9:2', 'Sanctuary', 'hard'),

-- ---- Baptism --------------------------------------------------------------
('Who baptized Jesus?', '["Peter", "John the Baptist", "Andrew", "Elijah"]'::jsonb, 1, 'Jesus came from Galilee to Jordan unto John, to be baptized of him.', 'Matthew 3:13-16', 'Baptism', 'easy'),
('In which river was Jesus baptized?', '["The Nile", "The Euphrates", "The Jordan", "The Kishon"]'::jsonb, 2, 'He was baptized of John in Jordan.', 'Mark 1:9', 'Baptism', 'easy'),
('What happened when Jesus came up out of the water?', '["A rainbow appeared", "The Spirit descended like a dove and a voice spoke from heaven", "An earthquake shook the river", "The crowd fled"]'::jsonb, 1, '"This is my beloved Son, in whom I am well pleased."', 'Matthew 3:16-17', 'Baptism', 'easy'),
('What does baptism by immersion represent?', '["A church membership fee", "Death, burial and resurrection with Christ", "The washing of the feet", "A public promise to tithe"]'::jsonb, 1, '"We are buried with him by baptism into death."', 'Romans 6:3-4', 'Baptism', 'medium'),
('In whose name did Jesus command believers to be baptized?', '["The Father, and of the Son, and of the Holy Ghost", "Moses and the prophets", "The apostles", "The church"]'::jsonb, 0, 'The Great Commission names all three Persons of the Godhead.', 'Matthew 28:19', 'Baptism', 'easy'),
('Peter said "Repent, and be baptized every one of you" — for what?', '["For a blessing", "For the remission of sins", "For church office", "For healing"]'::jsonb, 1, '"...and ye shall receive the gift of the Holy Ghost."', 'Acts 2:38', 'Baptism', 'medium'),
('Whom did Philip baptize on the road to Gaza?', '["Cornelius", "The Ethiopian eunuch", "Lydia", "The Philippian jailer"]'::jsonb, 1, 'They went down both into the water, and he baptized him.', 'Acts 8:38', 'Baptism', 'medium'),
('What did the Ethiopian confess before he was baptized?', '["I believe that Jesus Christ is the Son of God", "I will keep the law", "I will give all my goods", "I have seen a vision"]'::jsonb, 0, 'Belief comes before baptism.', 'Acts 8:37', 'Baptism', 'medium'),
('Who was baptized at midnight after an earthquake opened the prison?', '["Cornelius", "The Philippian jailer and his household", "Simon the sorcerer", "Crispus"]'::jsonb, 1, 'He washed their stripes, and was baptized, he and all his, straightway.', 'Acts 16:33', 'Baptism', 'hard'),
('About how old was Jesus when He was baptized?', '["About twenty", "About thirty", "About forty", "About twelve"]'::jsonb, 1, '"Jesus himself began to be about thirty years of age."', 'Luke 3:23', 'Baptism', 'medium'),
('Complete: "One Lord, one faith, one ___."', '["church", "baptism", "law", "hope"]'::jsonb, 1, 'Paul lists the unities that bind the body of Christ.', 'Ephesians 4:5', 'Baptism', 'medium'),
('Who said "I have need to be baptized of thee, and comest thou to me?"', '["Peter", "John the Baptist", "Nicodemus", "Andrew"]'::jsonb, 1, 'John hesitated, but Jesus said, "Suffer it to be so now."', 'Matthew 3:14-15', 'Baptism', 'hard'),

-- ---- State of the Dead ----------------------------------------------------
('What did Jesus call the death of Lazarus?', '["A judgment", "Sleep", "A punishment", "A mystery"]'::jsonb, 1, '"Our friend Lazarus sleepeth; but I go, that I may awake him."', 'John 11:11-14', 'State of the Dead', 'easy'),
('Which book says "the dead know not any thing"?', '["Job", "Psalms", "Ecclesiastes", "Proverbs"]'::jsonb, 2, '"For the living know that they shall die: but the dead know not any thing."', 'Ecclesiastes 9:5', 'State of the Dead', 'medium'),
('According to Psalm 146:4, what happens to a person''s thoughts at death?', '["They continue in heaven", "They perish", "They are recorded", "They are transferred"]'::jsonb, 1, '"His breath goeth forth... in that very day his thoughts perish."', 'Psalm 146:4', 'State of the Dead', 'medium'),
('When did man become a living soul?', '["When God breathed into him the breath of life", "When he ate the fruit", "When he was named", "When Eve was created"]'::jsonb, 0, 'Dust plus the breath of life equals a living soul — man does not have one separately.', 'Genesis 2:7', 'State of the Dead', 'medium'),
('At death, where does the spirit (breath) return?', '["To the grave", "Unto God who gave it", "To the stars", "To the family"]'::jsonb, 1, 'The dust returns to the earth, and the spirit returns unto God.', 'Ecclesiastes 12:7', 'State of the Dead', 'medium'),
('Who rises first when Jesus returns?', '["The great men of the earth", "The dead in Christ", "The living saints", "The wicked"]'::jsonb, 1, '"The dead in Christ shall rise first."', '1 Thessalonians 4:16', 'State of the Dead', 'medium'),
('When do the righteous put on immortality?', '["At death", "At the last trump, at the resurrection", "At baptism", "At conversion"]'::jsonb, 1, '"This mortal must put on immortality" — at the last trump.', '1 Corinthians 15:51-54', 'State of the Dead', 'medium'),
('Who alone has immortality according to Paul?', '["The angels", "God", "The prophets", "The redeemed"]'::jsonb, 1, '"Who only hath immortality, dwelling in the light which no man can approach unto."', '1 Timothy 6:16', 'State of the Dead', 'hard'),
('What is the "second death" in Revelation?', '["A second judgment", "The lake of fire — the final end of the wicked", "A spiritual decline", "The death of the body"]'::jsonb, 1, 'Death and hell are cast into the lake of fire — sin ends forever.', 'Revelation 20:14', 'State of the Dead', 'medium'),
('Jesus said the hour is coming when all that are in the graves shall hear what?', '["The trumpet", "His voice", "The angels", "The thunder"]'::jsonb, 1, '"All that are in the graves shall hear his voice, and shall come forth."', 'John 5:28-29', 'State of the Dead', 'medium'),
('Whom did Saul consult at Endor, contrary to God''s command?', '["A prophet", "A woman with a familiar spirit", "The high priest", "Samuel himself"]'::jsonb, 1, 'Saul sought a medium, and it cost him his life.', '1 Samuel 28:7', 'State of the Dead', 'hard'),
('According to Isaiah 8:19-20, to whom should a people seek?', '["To wizards that peep and mutter", "Unto their God, to the law and to the testimony", "To the dead", "To the elders"]'::jsonb, 1, '"If they speak not according to this word, it is because there is no light in them."', 'Isaiah 8:19-20', 'State of the Dead', 'hard'),
('Do the dead praise the Lord, according to Psalm 115:17?', '["Yes, continually", "No — the dead praise not the LORD", "Only the righteous do", "The psalm does not say"]'::jsonb, 1, '"The dead praise not the LORD, neither any that go down into silence."', 'Psalm 115:17', 'State of the Dead', 'medium'),

-- ---- Creation -------------------------------------------------------------
('On which day did God create the sun, moon and stars?', '["The first", "The second", "The third", "The fourth"]'::jsonb, 3, 'The lights in the firmament were made on the fourth day.', 'Genesis 1:14-19', 'Creation', 'medium'),
('On which day were the fish and birds created?', '["The third", "The fourth", "The fifth", "The sixth"]'::jsonb, 2, 'The waters brought forth abundantly, and fowl flew above the earth.', 'Genesis 1:20-23', 'Creation', 'medium'),
('From what did God form man?', '["Clay from the river", "The dust of the ground", "Water", "A tree"]'::jsonb, 1, 'God formed man of the dust of the ground and breathed life into him.', 'Genesis 2:7', 'Creation', 'easy'),
('From what did God make Eve?', '["The dust", "A rib taken from Adam", "A breath", "The garden soil"]'::jsonb, 1, 'God took one of Adam''s ribs and made a woman.', 'Genesis 2:21-22', 'Creation', 'easy'),
('What did God do on the seventh day?', '["Created the angels", "Rested, and blessed and sanctified the day", "Planted the garden", "Named the animals"]'::jsonb, 1, 'He rested, blessed the seventh day and sanctified it.', 'Genesis 2:2-3', 'Creation', 'easy'),
('In whose image was man created?', '["The angels''", "God''s own image", "The animals''", "No image is mentioned"]'::jsonb, 1, '"So God created man in his own image... male and female created he them."', 'Genesis 1:27', 'Creation', 'easy'),
('What was the first thing God declared "not good"?', '["The darkness", "That the man should be alone", "The serpent", "The barren ground"]'::jsonb, 1, '"I will make him an help meet for him."', 'Genesis 2:18', 'Creation', 'medium'),
('Who named the animals?', '["God", "Adam", "Eve", "The angels"]'::jsonb, 1, 'Whatsoever Adam called every living creature, that was the name thereof.', 'Genesis 2:19-20', 'Creation', 'medium'),
('What food did God give man at creation?', '["Every herb bearing seed and the fruit of trees", "Fish and fowl", "Bread and wine", "Milk and honey"]'::jsonb, 0, 'The original diet was fruit, grain, nuts and seeds.', 'Genesis 1:29', 'Creation', 'medium'),
('Which two trees are named in the midst of the garden?', '["The olive and the fig", "The tree of life and the tree of knowledge of good and evil", "The cedar and the palm", "The vine and the almond"]'::jsonb, 1, 'One gave life; the other was the test of loyalty.', 'Genesis 2:9', 'Creation', 'medium'),
('How did God bring the world into existence?', '["Over long ages of chance", "He spoke, and it was done", "By shaping existing matter", "The Bible does not say"]'::jsonb, 1, '"For he spake, and it was done; he commanded, and it stood fast."', 'Psalm 33:9', 'Creation', 'easy'),

-- ---- Second Coming --------------------------------------------------------
('Who told the disciples that Jesus would return "in like manner"?', '["Peter", "Two men in white apparel", "Moses and Elijah", "The high priest"]'::jsonb, 1, 'As they gazed up at His ascension, angels gave the promise.', 'Acts 1:10-11', 'Second Coming', 'medium'),
('What sounds accompany the return of Jesus?', '["Silence", "A shout, the voice of the archangel, and the trump of God", "Only thunder", "A still small voice"]'::jsonb, 1, 'The Lord Himself shall descend from heaven with a shout.', '1 Thessalonians 4:16', 'Second Coming', 'medium'),
('Who knows the day and hour of Christ''s return?', '["The angels", "The prophets", "No man — only the Father", "The church"]'::jsonb, 2, '"But of that day and hour knoweth no man, no, not the angels of heaven."', 'Matthew 24:36', 'Second Coming', 'easy'),
('What did Jesus promise before He left?', '["That He would send a prophet", "That He would come again and receive us unto Himself", "That the temple would stand", "That the disciples would rule"]'::jsonb, 1, '"I go to prepare a place for you... I will come again."', 'John 14:2-3', 'Second Coming', 'easy'),
('What happens to the living righteous at His coming?', '["They remain on earth", "They are caught up together to meet the Lord in the air", "They sleep first", "They rebuild Jerusalem"]'::jsonb, 1, 'Together with the resurrected dead, to be forever with the Lord.', '1 Thessalonians 4:17', 'Second Coming', 'medium'),
('How does Jesus describe the manner of His coming in Matthew 24:27?', '["As a thief no one sees", "As lightning shining from the east unto the west", "As a whisper", "As a slow dawn"]'::jsonb, 1, 'Unmistakable and worldwide — not secret.', 'Matthew 24:27', 'Second Coming', 'medium'),
('What is "that blessed hope" Paul writes of to Titus?', '["The resurrection of Israel", "The glorious appearing of the great God and our Saviour Jesus Christ", "The rebuilding of the temple", "The end of persecution"]'::jsonb, 1, 'The second advent is the church''s blessed hope.', 'Titus 2:13', 'Second Coming', 'medium'),
('Who comes with Jesus when He returns?', '["The prophets", "All the holy angels", "The apostles", "No one"]'::jsonb, 1, '"When the Son of man shall come in his glory, and all the holy angels with him."', 'Matthew 25:31', 'Second Coming', 'medium'),
('What must happen before the end comes, according to Matthew 24:14?', '["The temple must be rebuilt", "The gospel must be preached in all the world", "Israel must be restored", "The nations must disarm"]'::jsonb, 1, '"And then shall the end come."', 'Matthew 24:14', 'Second Coming', 'medium'),
('What are believers repeatedly told to do concerning His return?', '["Calculate the date", "Watch and be ready", "Withdraw from society", "Wait quietly at home"]'::jsonb, 1, '"Therefore be ye also ready: for in such an hour as ye think not the Son of man cometh."', 'Matthew 24:42-44', 'Second Coming', 'easy'),
('What happens to the wicked at the brightness of His coming?', '["They are given another chance", "They are consumed and destroyed", "They flee to the mountains and survive", "They are taken captive"]'::jsonb, 1, '"Whom the Lord shall consume with the spirit of his mouth."', '2 Thessalonians 2:8', 'Second Coming', 'hard'),
('What will the righteous receive at the last trump?', '["Earthly kingdoms", "Incorruptible, immortal bodies", "New names only", "A thousand-year rest on earth first"]'::jsonb, 1, '"We shall be changed... this mortal must put on immortality."', '1 Corinthians 15:52-53', 'Second Coming', 'medium'),
('Complete: "Behold, he cometh with clouds; and every eye shall ___ him."', '["hear", "see", "fear", "seek"]'::jsonb, 1, 'His return is literal, visible and universal.', 'Revelation 1:7', 'Second Coming', 'easy'),
('Where does Jesus take the redeemed after He comes?', '["To a restored Jerusalem on earth", "To the Father''s house", "To the wilderness", "To the sea of glass only"]'::jsonb, 1, '"In my Father''s house are many mansions... I will come again, and receive you unto myself."', 'John 14:2-3', 'Second Coming', 'medium');

-- Safety net: these batches were written against a bank that already held
-- 158 questions, and seven of them collided with existing rows. Re-running
-- any of these files is now harmless.
delete from public.quiz_questions q
 where q.id > (select min(q2.id) from public.quiz_questions q2
                where q2.question = q.question);
